_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

product_update:
    path: /product/update/{id}
    controller: App\Controller\ProductController::updateAction
    methods: [POST]
